version: '3.2'

services:
  bitcoind:
    container_name: rgb-bitcoind
    image: registry.gitlab.com/hashbeam/docker/bitcoind:24.0
    command: "-fallbackfee=0.0002"
    environment:
      MYUID: 1000
      MYGID: 1000
    volumes:
      - ./datacore:/srv/app/.bitcoin
  electrs:
    container_name: rgb-electrs
    image: registry.gitlab.com/hashbeam/docker/electrs:0.9.9
    environment:
      MYUID: 1000
      MYGID: 1000
    volumes:
      - ./dataindex:/srv/app/db
    depends_on:
      - bitcoind
    ports:
      - 50001:50001
