version: '3.8'

services:
  esplora:
    image: blockstream/esplora:956c74f42eb6ad803d8aedc272ba83d3aa6dcf5c
    command: /srv/explorer/run.sh bitcoin-regtest explorer
    environment:
      DEBUG: verbose
      NO_PRECACHE: 1
      NO_ADDRESS_SEARCH: 1
      NO_REGTEST_MINING: 1
    volumes:
      - ./dataesplora:/data
    ports:
      - 50001:50001
      - 8094:80
