version: '3.8'

services:
  esplora:
    # TODO: use a fixed known-working image instead of latest
    image: blockstream/esplora:latest
    command: /srv/explorer/run.sh bitcoin-regtest explorer
    environment:
      DEBUG: verbose
      NO_PRECACHE: 1
      NO_ADDRESS_SEARCH: 1
      NO_REGTEST_MINING: 1
    volumes:
      - ./dataesplora:/data
    ports:
      - 50001:50001
      - 8094:80
